### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by dfisheritp** [fluffy-mods/WorkTab#121] opened 2019-10-04 04:07 UTC
I need to invest in some glasses but the UI for the work tab seems to be hard coded and does not work when enlarging the scale. On an ultrawide 29' (~2.5k x ~1k pixels) screen it's very difficult to read.

I enlarged the UI scale to 1.25 and it's all sorts of wonky.

Looking for something about 10-15% larger so I can read the subcategories.

**Comment by ionstorm66** [comment] 2019-10-11 03:42
Duplicate of #77

**Closed** 2020-01-19 20:08 UTC
